apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: krvnb/my-docker-image:1.0.0
    ports:
    - containerPort: 9090
    command: ["java","-jar","/target/trail-0.0.1-SNAPSHOT.jar"]

